name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: 17  # Убедитесь, что используется Java 17 для совместимости с Android Gradle Plugin
      ANDROID_COMPILE_SDK: 33
      ANDROID_BUILD_TOOLS: "33.0.2"
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Инициализация и обновление всех сабмодулей рекурсивно

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: ${{ env.ANDROID_COMPILE_SDK }}
          build-tools: ${{ env.ANDROID_BUILD_TOOLS }}
          components: |
            platforms;android-${{ env.ANDROID_COMPILE_SDK }}
            build-tools;${{ env.ANDROID_BUILD_TOOLS }}
            platform-tools

      - name: Initialize and update submodules
        run: |
          git submodule update --init --recursive --remote
          echo "Waiting for submodules to be ready..."
          for i in {1..5}; do
            [ -d "path/to/submodule" ] && echo "Submodule ready." && break || echo "Retry $i" && sleep 5
          done

      - name: Build project
        run: ./gradlew clean build --stacktrace

      - name: Run tests
        run: ./gradlew testDebugUnitTest --stacktrace
