name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Remove all existing submodule directories
        run: |
          echo "Removing all submodule directories..."
          git submodule foreach 'rm -rf $name && rm -rf .git/modules/$name || true'
          git config -l | grep '^submodule' | while read -r config; do
            section=$(echo $config | cut -d'=' -f1)
            git config --remove-section $section || true
          done

      - name: Reinitialize submodule
        run: |
          git submodule add --force https://github.com/TarasovVP/SubModuleProject.git submoduleproject
          git submodule update --init --recursive

      - name: Build project
        run: ./gradlew build --no-daemon
