name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update submodules
        run: |
          git submodule update --init --recursive

      - name: Verify Submodule Initialization
        run: |
          if [ ! -d "SubModuleProject" ]; then
            echo "Error: SubModuleProject directory not found after reinitialization." >&2
            exit 1
          fi
          echo "SubModuleProject is initialized."

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: '33.0.0'

      - name: List included modules
        run: ./gradlew listModules

      - name: Run Unit Tests
        run: ./gradlew test --no-daemon